services:
  # --- Base de Datos ---
  db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - TZ=Europe/Madrid

  # --- Backend ---
  api:
    build: ./api
    container_name: springboot_app
    depends_on:
      - db
    expose:
      - '8080' # Only visible to Nginx, not outside
    env_file:
      - .env
    restart: on-failure
    environment:
      - TZ=Europe/Madrid
      # Map for application.properties:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}

  # --- Frontend (Nginx) ---
  frontend:
    build: ./app
    container_name: vite_frontend
    depends_on:
      - api
    ports:
      - '80:80' # Only open port to the world
    restart: always

volumes:
  postgres-data:
